@echo off
echo Starting Uniccon Loan Approval Bot...
cd /d "C:\Users\HP\Desktop\Uniccon_AI_projects\Uniccon_Loan_Bot"
call venv\Scripts\activate
echo Virtual environment activated...
echo Starting Streamlit app...
streamlit run app.py
pause